# Generated by Django 4.0 on 2022-01-09 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_day_eight_alter_day_five_alter_day_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='bookings.service'),
        ),
    ]
